### ISSUE TITLE
gnatsd has some weird crashes when slapping with traffic

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#515] opened 2019-02-16 00:21 UTC
this is actually a little bit hard to reproduce so I wouldn't dig into it much yet unless someone asks

```
 ops load gnatsd_1.4.1 -p 4222
```

```
➜  tea  cat main.go
package main

import (
        "fmt"
        nats "github.com/nats-io/go-nats"
)

func main() {

        // Connect to a server
        nc, err := nats.Connect("nats://localhost:4222")
        if err != nil {
                fmt.Println(err)
        }

        fmt.Println("asdf")

        // Simple Publisher
        nc.Publish("foo", []byte("Hello World"))

        fmt.Println("asdf2")

        // Simple Async Subscriber
        nc.Subscribe("foo", func(m *nats.Msg) {
                fmt.Printf("Received a message: %s\n", string(m.Data))
        })

        fmt.Println("asdf3")

        nc.Close()

}
```

```
➜  tea  cat b.sh
#!/bin/bash
for i in `seq 1 300`;
do
  ./tea
done
```

```
[2] 2019/02/16 00:15:42.095787 [TRC] 10.0.2.2:63349 - cid:1502 - <<- [-ERR Unknown Protocol Operation]
[2] 2019/02/16 00:15:42.097275 [ERR] 10.0.2.2:63349 - cid:1502 - Client parser ERROR, state=0, i=0: proto='"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00"...'
runtime: epollwait on fd 4 failed with 107
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x879b36, 0x17)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/panic.go:608 +0x72
runtime.netpoll(0xc00001c001, 0x1)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/netpoll_epoll.go:75 +0x215
runtime.findrunnable(0xc00001c000, 0x0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:2469 +0x51c
runtime.schedule()
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:2613 +0x13a
runtime.goexit0(0xc000460600)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/proc.go:2790 +0x1f2
runtime.mcall(0x430700)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7000084f30, 0x72, 0x0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0000ca418, 0x72, 0xc000048000, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0000ca418, 0xffffffffffffff00, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc0000ca400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/internal/poll/fd_unix.go:384 +0x1a0
net.(*netFD).accept(0xc0000ca400, 0x42ab72, 0xc000000008, 0x890228)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00000c098, 0x77a09b, 0xc0000da030, 0x890228)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/net/tcpsock_posix.go:139 +0x2e
net.(*TCPListener).Accept(0xc00000c098, 0xc00027a201, 0xc00000c078, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/net/tcpsock.go:260 +0x47
github.com/nats-io/gnatsd/server.(*Server).AcceptLoop(0xc0000da000, 0x0)
        /home/travis/gopath/src/github.com/nats-io/gnatsd/server/server.go:521 +0x6ba
github.com/nats-io/gnatsd/server.(*Server).Start(0xc0000da000)
        /home/travis/gopath/src/github.com/nats-io/gnatsd/server/server.go:350 +0x3d9
github.com/nats-io/gnatsd/server.Run(0xc0000da000, 0xc0000da000, 0x1)
        /home/travis/gopath/src/github.com/nats-io/gnatsd/server/service.go:21 +0x2b
main.main()
        /home/travis/gopath/src/github.com/nats-io/gnatsd/main.go:100 +0x10e

goroutine 6 [syscall, 10 minutes]:
os/signal.signal_recv(0x0)
        /home/travis/.gimme/versions/go1.11.5.linux.amd64/src/runtime/sigqueue.go:139 +0x9c
```

**Comment by francescolavra** [comment] 2021-01-14 11:29
I couldn't reproduce the issue, ran the client program with thousands of iterations and the server never errored out; I ran this stress test with the client doing either a subscribe after a publish, or a publish after a subscribe.
I assume this has been fixed sometime in the past, closing.

**Closed** 2021-01-14 11:29 UTC
