### ISSUE TITLE
node crashing on pagecache writes

### ISSUE THREAD

**Issue by zeroecco** [nanovms/nanos#1851] opened 2023-05-09 23:56 UTC
hello! looks like there is a write issue. tried latest nanos and nightly:
```
INFO [05-09|23:53:39.332] Syncing beacon headers                   downloaded=13,731,840 left=3,494,356  eta=3m50.097s
ERROR[05-09|23:53:39.574] Empty cpu stats 
ERROR[05-09|23:53:42.577] Empty cpu stats 

frame trace: 
ffffc000027ffcd0:   ffffffff8008ac28    (extents_range_handler + 00000000000005f8/00000000000007bf)
ffffc000027ffdc0:   ffffffff8008af91    (filesystem_check_or_reserve_extent + 0000000000000051/00000000000000a9)
ffffc000027ffde0:   ffffffff8004de6b    (pagecache_write_sg + 00000000000000eb/000000000000054e)
ffffc000027fff00:   ffffffff800cbc43    (file_write + 0000000000000183/000000000000045b)
ffffc000027fff80:   ffffffff800ce9d9    (write + 0000000000000189/0000000000000277)
ffffc000027fffb0:   ffffffff800d758a    (syscall_handler + 00000000000002ca/00000000000005b9)

loaded klibs: 
assertion oldval failed at /home/circleci/project/src/tfs/tfs.c:877  in update_extent(); halt
```

If I can provide anymore information please lmk and I will be glad to

**Comment by zeroecco** [comment] 2023-05-10 00:27
another crash within pagecache iself:
```
INFO [05-10|00:23:55.389] Syncing: chain download in progress      synced=0.09% chain=5.08MiB headers=53248@4.29MiB bodies=14877@681.52KiB receipts=14877@130.77KiB eta=4h25m48.065s
ERROR[05-10|00:23:56.870] Empty cpu stats 

frame trace: 
ffffc00001237de0:   ffffffff8007942a    (traverse_postorder + 000000000000026a/0000000000000406)
ffffc00001237e40:   ffffffff80079467    (traverse_postorder + 00000000000002a7/0000000000000406)
ffffc00001237ea0:   ffffffff8007aa10    (destruct_rbtree + 00000000000001a0/00000000000001bd)
ffffc00001237ef0:   ffffffff8004b5ac    (pagecache_node_free + 00000000000001ac/0000000000000290)
ffffc00001237f50:   ffffffff80053ea2    (runloop_internal + 00000000000002c2/00000000000009e8)
ffffc00001237fc0:   ffffffff80042263    (context_switch_finish + 0000000000000083/00000000000001bc)

loaded klibs: 
assertion page_state(pp) == PAGECACHE_PAGESTATE_FREE failed at /home/circleci/project/src/kernel/pagecache.c:1515  in pagecache_page_release(); halt
```

**Comment by zeroecco** [comment] 2023-05-10 00:53
okay I think I know what is going on.

Locally I test my configs out using `ops run`. this leads to issues like:

```
Fatal: Failed to register the Ethereum service: write /root/.ethereum/geth/chaindata/MANIFEST-000000: no space left on device
```
to combat this issue I add `"BaseVolumeSz": "1g"` to my ops.config file.

I am not sure, but I _think_ by setting that value, it fixes the unikernel disk to that image permanently. When we go to deploy to AWS, setting the EBS size in this context will have no effect size I set `BaseVolumeSz`. I have read the ops code to check yet. but that is what my best guess is right now.

**Comment by zeroecco** [comment] 2023-05-10 02:32
welp that wasn't it :(

**Comment by zeroecco** [comment] 2023-05-10 20:01
@eyberg Prebuilt volumes were an option we ran with for a bit but were still too slow for our needs. 

to be 100% clear the total download is ~895GB, and takes geth usually 24 hours to build from the p2p network. go-ethereum's levelDB is ~350GB (the part we want in memory) and the archive is the remainder (we want on disk). With geth, you need both lock step. if leveldb is in memory, many operations in geth become significantly faster. 

AWS EBS is so slow that loading all those files into memory with EBS's gp3 @ 125mb/s (the default) will take ~2800 seconds before geth can start. This is unacceptable for our use case. The solution i have now is that on a traditional VM I can expand linux's tmpfs on `/dev/shm` to the required size.  another node I have "hot" with this data in memory can transfer that data at near rated wires speeds without EBS slowing us down.

**Comment by eyberg** [comment] 2023-05-10 22:52
are you booting instances with enough memory for that (eg: something like a r4/r5 or higher) ? it'd be good if you can expand on the underlying use-case of loading all this in mem and not caring if it never makes it to disk (i get the fast-start-time desire) but kinda feel there are probably better ways to get at it

**Comment by zeroecco** [comment] 2023-05-11 18:55
we def are building instances that are large enough for this. LevelDB/PebbleDB are meant to be persistent, and thus has strong guarantees to write to disk in place to ensure recoverability. This is sub optimal for our internal use case (I cannot expand beyond that). The shortcut answer for the time being has been to use tmpfs to "fake" very very fast storage. 

If I can be any help in diagnosing the kernel bug please let me know. I am so close to having this online that I can barely contain myself.

**Comment by zeroecco** [comment] 2023-05-17 20:43
Is there anything else I can provide here for this bug report?

**Comment by eyberg** [comment] 2023-05-17 22:54
just so we know - you did or did not try this on an instance with enough space? and it worked or didn't and that is how you got the crash?

we haven't had time to look at it yet; but the best way to solve (at least the 2 issues you posted first) would get the minimal reproducing example (eg: it'd be great to repro w/out geth downloading 800g) - at least for the first 2 issues you are more than likely hitting a mem/disk limit and it very well could be on how geth is writing

in this case we're assuming it is an instance w/a large enough volume (either base volume or aux mountable one, (prior's prob easiest to repro))

that volume can be empty at first (which is insanely faster than one with existing data); then - start doing buffered writes to it and see where it crashes (can easily just be a limit you are hitting) - as the tmpfs hack is not something that would work today in nanos we can just focus in on the main issue

i can take a look later on but something along these lines (on appropriately sized instance)

```
{
        "BaseVolumeSz": "50g"
}
```

```
package main

import (
	"fmt"
	"log"
	"os"
)

func main() {

	f, err := os.Create("foo.bar")
	if err != nil {
		fmt.Println(err)
	}

	if err := f.Truncate(4e10); err != nil {
		fmt.Println(err)
	}

	fmt.Println("test")
}
```

(you prob actually want a buffered io (eg: bufio)  not truncate)

**Comment by zeroecco** [comment] 2023-05-18 15:34
understood!

The repro is as follows:
ops.config
```json
{
  "RebootOnExit": true,
  "BaseVolumeSz": "50g",
  "ManifestPassthrough": {
    "consoles": [
      "+net",
      "-vga",
      "-serial"
    ],
    "so_rcvbuf": "524288" << Happens with or without this
  },
  "RunConfig": {
    "Ports": [
      "8551",
      "8545",
      "8546",
      "30303",
      "6060"
    ]
  },
  "Files": ["jwtsecret"],
  "CloudConfig": {
    "Platform": "aws",
    "ProjectID": "geth",
    "Flavor": "c6a.2xlarge",
    "BucketName": "BUCKET_NAME",
    "Zone": "us-east-1",
    "Tags": [
      {
        "key": "release_tag",
        "value": "1.11.5"
      }
    ]
  },
  "Args": [
    "--authrpc.jwtsecret",
    "/jwtsecret",
    "--http.addr",
    "0.0.0.0",
    "--authrpc.addr",
    "0.0.0.0",
    "--ws.addr",
    "0.0.0.0",
    "--cache",
    "8192"
  ]

}
```

the jwtsecret file:

```bash
cat jwtsecret
0xc412699c29e689537ba4c646d264a5cfd7c0a60c346793dd2b1c78bf00b81865
```

Pull the geth and lighthouse codebases, compile 

Fire up geth:

```bash
ops run -c ops.config geth
```

fire up lighthouse:

```bash
lighthouse bn --checkpoint-sync-url "https://mainnet.checkpoint.sigp.io" --execution-endpoint http://IP_ADDRESS_OF_UNIKERNEL:8551 --execution-jwt-secret-key 0xc412699c29e689537ba4c646d264a5cfd7c0a60c346793dd2b1c78bf00b81865
```

wait for 30-40 minutes, geth will crash and hang (no auto restart)

**Comment by eyberg** [comment] 2023-05-18 19:39
doesn't this download more than 50g? shouldn't that basevolume be at least 350gb or 900?

**Comment by zeroecco** [comment] 2023-05-18 19:58
it takes days to download that much, it will fail long before then

**Comment by eyberg** [comment] 2023-05-18 21:16
ok, so are you saying it's failing much earlier before it runs out of disk space?

**Comment by zeroecco** [comment] 2023-05-18 21:50
yep! :)

**Comment by eyberg** [comment] 2023-05-19 03:29
so you're not specifying a memory limit here - when deploying as a normal vm to aws it'll use the total size of the instance memory given but in this case you are running on top of an existing vm and so the default set via ops is only 2g; this isn't enough for what geth is doing

I can reliably get a GPF usually during a fsync on that setting fairly quickly (within minutes) using something similar instance-size type (c5a.2xlarge); setting it to 6g lets it run much longer and gets to ~3g mark - but the problem is the memory setting is way too low for geth - as to why that's happening i ran into https://github.com/ethereum/go-ethereum/issues/20383 - idk if there is a config setting that can be set to change this behavior?

**Comment by zeroecco** [comment] 2023-05-24 03:03
its possible. I will keep trying. But I straight up broke my local ops (on m1) and haven't beenable to get it back yet

**Comment by francescolavra** [comment] 2023-06-02 15:49
In https://github.com/nanovms/nanos/pull/1861, we made a number of changes to the kernel code to fix the above issues and improve scalability of the kernel on instances with large memory size and large volumes.
More specifically, the "assertion oldval failed at /home/circleci/project/src/tfs/tfs.c:877  in update_extent()" crash is fixed by https://github.com/nanovms/nanos/pull/1861/commits/9c80866491bcda43e7e059f64c9f283969e2c718, and the "assertion page_state(pp) == PAGECACHE_PAGESTATE_FREE failed at /home/circleci/project/src/kernel/pagecache.c:1515  in pagecache_page_release()" crash is fixed by https://github.com/nanovms/nanos/pull/1861/commits/af131aaa2bec0ac9487b68736740b0239e322228

**Closed** 2023-06-08 08:50 UTC
