### ISSUE TITLE
node.js failure if stack located in high half of lowest 4gb

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#771] opened 2019-04-25 14:03 UTC
This is just to track what could possibly be an issue with stack setup. This issue arose while implementing ASLR. Previously, the stack would be allocated in the lower portion of 0x100000000-0x1ffffffffff (4gb to 5gb). By observation, with ASLR, running the go node test whenever the stack was located above 0x180000000, the go node test would fail with the following:

```
=== RUN   TestNodeHelloWorld
Extracting /home/wjhun/.ops/packages/node_v11.5.0.tar.gz...
[node js/hello.js]
assigned: 10.0.2.15
path.js:1077
        path = process.cwd();
                       ^

Error: ENOSYS: function not implemented, uv_cwd
    at Object.resolve (path.js:1077:24)
    at Function.Module._initPaths (internal/modules/cjs/loader.js:805:22)
    at internal/modules/cjs/loader.js:845:8
    at NativeModule.compile (internal/bootstrap/loaders.js:340:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:201:18)
    at setupInspector (internal/bootstrap/node.js:577:36)
    at setupGlobalConsole (internal/bootstrap/node.js:498:5)
    at startup (internal/bootstrap/node.js:127:7)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
--- FAIL: TestNodeHelloWorld (6.82s)
    common.go:86: Expected text not found
FAIL
exit status 1
FAIL    _/share/src/nanovms/ku0/test/go 17.883s
Makefile:14: recipe for target 'test' failed
make[2]: *** [test] Error 1
make[2]: Leaving directory '/share/src/nanovms/ku0/test/go'
Makefile:7: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/share/src/nanovms/ku0/test'
Makefile:70: recipe for target 'test' failed
make: *** [test] Error 2
```

Strangely, this is reproducible in master by moving the virtual32 heap into the 0x80000000 space (below 4gb threshold, but in both cases bit 31 is set):

```
diff --git a/src/unix/unix_internal.h b/src/unix/unix_internal.h
index 7ec9f6f..812c2de 100644
--- a/src/unix/unix_internal.h
+++ b/src/unix/unix_internal.h
@@ -10,7 +10,7 @@
 #define PROCESS_VIRTUAL_HEAP_START      0x7000000000ull
 #define PROCESS_VIRTUAL_HEAP_LENGTH     0x10000000000ull
 #define PROCESS_VIRTUAL_HEAP_END        (PROCESS_VIRTUAL_HEAP_START + PROCESS_VIRTUAL_HEAP_LENGTH - 1)
-#define PROCESS_VIRTUAL_32_HEAP_START   0x6f000000
+#define PROCESS_VIRTUAL_32_HEAP_START   0x8f000000
 #define PROCESS_VIRTUAL_32_HEAP_LENGTH  0x10000000
 #define PROCESS_VIRTUAL_32_HEAP_END     (PROCESS_VIRTUAL_32_HEAP_START + PROCESS_VIRTUAL_32_HEAP_LENGTH - 1)
```

As far as I'm aware, we should be able to place the stack anywhere, and staying within the lowest 2gb is probably just masking the real cause.

**Comment by francescolavra** [comment] 2021-01-04 11:22
I'm unable to reproduce the issue with current master.
In src/unix/exec.c, at the line `u64 stack_start = 0x80000000 - PROCESS_STACK_SIZE;`, I tried changing 0x80000000 to values in the 2gb to 4gb range, such as 0x90000000 and 0x100000000, and then ran `make && make test -C test/go/`. The TestNodeHelloWorld test (as well as the Go tests) always runs successfully.

**Comment by eyberg** [comment] 2022-08-05 16:27
closing as irreproducible/old

**Closed by eyberg** 2022-08-05 16:27 UTC
Labels: verify, node
