### ISSUE TITLE
nodejs >= v11.6.0 does not work

### ISSUE THREAD

**Issue by mkhon** [nanovms/nanos#340] opened 2019-01-06 19:26 UTC
nodejs 11.6.0 fails with

```
MODULE 1: looking for "/hi.js" in ["/lib/node"]
MODULE 1: load "/hi.js" for module "."
buffer.js:588
      if (encoding === 'utf8') return buf.utf8Slice(start, end);
                                          ^

RangeError: Index out of range
    at stringSlice (buffer.js:588:43)
    at Buffer.toString (buffer.js:658:10)
    at Object.readFileSync (fs.js:394:41)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:731:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
epoll_wait error: requested fd 11 (eventmask 19) missing check
epoll_wait error: requested fd 13 (eventmask 19) missing check
exit_groupexit status 1
```

**Comment by wjhun** [comment] 2019-10-31 20:01
This appears to be caused by a bug in qemu TCG code:

https://bugs.launchpad.net/qemu/+bug/1815423

https://git.qemu.org/?p=qemu.git;a=commitdiff_plain;h=1e8a98b53867f61da9ca09f411288e2085d323c4

Which explains the behavior @mkhon found above in https://github.com/nanovms/nanos/issues/340#issuecomment-451773167

**Comment by eyberg** [comment] 2019-11-20 20:56
we chose to not patch node or v8; closing as we have 12.13 working - we are forcing users to use up to date qemu or rely on hardware accel instead - also doc'd here 

https://github.com/nanovms/nanos/wiki/qemu

**Closed by eyberg** 2019-11-20 20:56 UTC
Labels: memory, node, qemu
