### ISSUE TITLE
Can't boot image on GCloud from osx

### ISSUE THREAD

**Issue by Littlelies** [nanovms/nanos#1085] opened 2020-03-06 16:27 UTC
I tried the hello world example on GCP (europe-west1-b) like described here: https://www.phpflow.com/golang/deploying-go-unikernels-to-google-cloud/, then the Mosquitto one from here: https://nanovms.com/dev/tutorials/unikernels-from-edge-cloud, they both run fine on my laptop running OS X, but GCP images won't boot.
Instance logs hang there:
```
found virtio-scsi at 0:3
virtio-scsi vendor='Google' product='PersistentDisk' rev='1' type=0 removable=0
virtio-scsi blksize=512 sectors=2097152 = 1024 MiB
drive 0x000f2210: PCHS=0/0/0 translation=lba LCHS=1024/32/63 s=2097152
Sending Seabios boot VM event.
Booting from Hard Disk 0...
ata_probe: IDENTIFY timeout

```
I never get the `assigned: x.x.x.x` line, so the VM is not usable. Would it be a networking configuration issue?

Ops version: 0.1.9
Nanos version: 0.1.23

**Comment by eyberg** [comment] 2020-03-06 16:35
sounds like you deployed it from mac? if so what macos version do you have?

can you try to deploy from linux and see if that works just to verify if that's indeed the issue?

it's not the first time we've heard this but are having trouble tracking down what the issue is

**Comment by Littlelies** [comment] 2020-03-06 21:04
Yes, running 10.15.3
From Linux it works!
I know GNU tar is not the same as OSX tar, so I'll try again on Mac using GNU tar and let you know.

**Comment by Littlelies** [comment] 2020-03-07 14:22
@eyberg : tar and zip happen in `ops` golang binary, not using the local tools, so wrong direction. If I move the golang binary from Linux to Mac and try to create the image, I get
```
% ops image create -c config.json mac80 -a main     
libpthread.so.0: file does not exist
```
Then I tried to just run it locally
```
% ops run -p 80 main                             
*errors.errorString libpthread.so.0: file does not exist
/Users/eyberg/go/src/github.com/nanovms/ops/lepton/ldd_darwin.go:100 (0x4caf019)
/Users/eyberg/go/src/github.com/nanovms/ops/lepton/ldd_darwin.go:129 (0x4caf91d)
/Users/eyberg/go/src/github.com/nanovms/ops/lepton/image.go:268 (0x4cac5ae)
```
So I moved the golang binary from my Mac to Linux, and creating the image and instance went well.
Conclusion: building the image on my Mac is broken, the issue might be related to this missing libpthread.so.0. I wish I could dig further...

**Comment by eyberg** [comment] 2020-03-09 02:44
once the disk image is built you can move that around from host to host hermetically - running 'ops run' locally will re-build the disk image

however, the go program on linux is prob. dynamically linked which is why it wants libpthread, if you wish to build that on mac you'll need to build GOOS=linux and then ops can load it from there - that most definitely should work - what I'm curious is if that works locally on your mac but then fails on gcloud

**Comment by Littlelies** [comment] 2020-03-09 08:09
It is the issue, yes.
```
% GOOS=linux go build -o main main.go
% ops run -p 80 main
```
Works locally on Mac, but not on cloud. So I guess this is more a ops issue, not nanos.

**Comment by eyberg** [comment] 2020-03-09 14:46
that's what you'd think but it's not the first time I've heard this - i'm kinda thinking there might be a mkfs issue - maybe @mkhon might be able to take a look

**Comment by Littlelies** [comment] 2020-03-11 09:27
For anyone interested in a workaround, using docker on osx, it works.
Use the following Dockerfile to build a working image:
```
FROM ubuntu:18.04
RUN apt-get update && apt-get -y install curl
RUN curl https://ops.city/get.sh -sSfL | sh
RUN /root/.ops/bin/ops update
ENV PATH="/root/.ops/bin:${PATH}"
```
Then launch `bash` with your local binary, config.json and service account file as shared volume(s), and follow the documentation to `export GOOGLE_APPLICATION_CREDENTIALS` and use the commands normally. FYI, images are in `/root/.ops/images` in the container.

**Comment by eyberg** [comment] 2020-03-11 19:23
started to do some git spelunking and seems that 323be1386835ccf4784150f33418b500c2cefac8 is the first time I can build on mac and deploy to gcloud (i can always weirdly build on linux and deploy up to and including master) -

**Comment by eyberg** [comment] 2020-03-11 19:40
so 1a9437ade504f369fd6753aa50d6e0f6af8b24a0 doesn't work

e5f9c652026650d52128bec7ba51b8e383499457 doesn't build on mac

and 4b02a62fe4e2ac9da5742ab21c446dbcd02fe7ec works

**Comment by mkhon** [comment] 2020-03-26 21:12
Fixed by #1097

**Closed** 2020-03-27 02:32 UTC
Labels: gcloud, infrastructure, macos, needs investigation

**Comment by mkhon** [comment] 2020-03-27 02:33
Root cause: %rcx clobbering by "rdtscp". clang 11 uses registers more aggressively than gcc or clang 10.

**Comment by Littlelies** [comment] 2020-03-27 16:00
I confirm it works on my Mac OS machine on Nanos 1.0.24, thank you very much.
