### ISSUE TITLE
AWs  image intermittent boot issue

### ISSUE THREAD

**Issue by jasonrichardsmith** [nanovms/nanos#1676] opened 2022-02-06 16:32 UTC
Sometimes my images boot like this in AWS.
![Screenshot(18)](https://user-images.githubusercontent.com/1245554/152690905-5291b112-e665-434a-94f6-12d5bf8e69c5.png)

If I terminate the instance, and it gets replaced with another instance, the next one usually works fine.
I have not noted any particular architecture or library that causes this.

I realize this is not a very helpful issue.

**Comment by eyberg** [comment] 2022-02-06 23:31
are you saying it sits there and continuously reboots only showing this output or is it perhaps crashing and rebooting immediately or it just gets stuck? is it a persistent program like a webserver or doing some one time task and shutting down?

**Comment by jasonrichardsmith** [comment] 2022-02-07 09:21
it appears to be just stuck there.  It also seems to occur across any of the images I create. It is so intermittent I have not been able to lock down a pattern. The EC2 instance never leaves the "initializing" state. Upon termination, the asg will spin up a new machine with the same AMI and that one will boot fine.

**Comment by jasonrichardsmith** [comment] 2022-02-07 09:22
these are all persistent services.

**Comment by eyberg** [comment] 2022-02-07 15:36
this is only happening with asg's not individual instances made with 'ops instance create'? if you can replicate with a particular workload we could probably drill into it more

**Comment by jasonrichardsmith** [comment] 2022-02-08 05:28
I will stand up my stack again and try to record its behavior.

**Comment by sanderssj** [comment] 2022-02-08 22:15
Hi @jasonrichardsmith 
Are you using nightly nanos builds? I tried to duplicate your problem and did not see a hang when I used a nightly after about 20 boots, but I did see one with nanos release 0.1.38 after six boots. The problem may have been fixed since that release.  If you have been seeing the problem with the nightlies then I'll keep trying to reproduce. Thanks!

**Comment by eyberg** [comment] 2022-08-05 16:26
closing - please re-open if you're still having trouble w/latest nightly

**Closed by eyberg** 2022-08-05 16:26 UTC
Labels: verify, question
