### ISSUE TITLE
process has cwd but not pwd

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#146] opened 2018-10-11 21:24 UTC
see also https://github.com/nanovms/nanos/issues/144

https://github.com/nanovms/nanos/blob/master/unix/unix_internal.h#L81

**Comment by samantha3pen** [comment] 2020-11-29 00:43
Hi @eyberg , my team members and I are students at the University of Texas at Austin. We are interested in contributing to Nanos as a part of a project for our virtualization class. Is this issue still available for us to work on? Could we take on this issue?

**Comment by eyberg** [comment] 2020-11-30 22:31
I think this is old/invalid as this works as expected ->

```
#include <unistd.h>
#include <stdio.h>

int main() {
    char cwd[1024];

    getcwd(cwd, sizeof(cwd));
    printf("Current working dir: %s\n", cwd);

    chdir("/tmp/somethingdiff");
    getcwd(cwd, sizeof(cwd));
    printf("Current working dir: %s\n", cwd);
}
```

not even sure why this tkt exists but cc @wjhun || @francescolavra - maybe we can close this?

**Comment by wjhun** [comment] 2020-12-01 06:43
The meaning of the issue isn't clear to me here ... pwd is either a command to print the current working directory or an env var (PWD) to cache it. I think it's fine to close this.

**Closed by wjhun** 2020-12-01 06:43 UTC
Labels: filesystem, good first issue, verify
