### ISSUE TITLE
openjre8 hangs on exit if run with tracing enabled

### ISSUE THREAD

**Issue by mkhon** [nanovms/nanos#727] opened 2019-04-09 10:39 UTC
openjre8-hello.json:

```
{
    "Files": [ "Hello.class", "/lib/x86_64-linux-gnu/libgcc_s.so.1", "/lib/x86_64-linux-gnu/librt.so.1", "/lib/x86_64-linux-gnu/libm.so.6", "/usr/lib/x86_64-linux-gnu/libstdc++.so.6" ],
    "Dirs": [ "/usr/lib/jvm/java-8-openjdk-amd64/jre" ],
    "Args": [ "java", "Hello" ]
}
```

Log:
```
ops/ops run -m openjre8-hello.manifest -c openjre8-hello.json -x -v -d /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
...
        2 write
Hello, world        2 direct return: 12, rsp 0x70020fd300
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fec88
        2 write

        2 direct return: 1, rsp 0x70020fd360
        2 mmap
        2 mmap: target 0x0000007002001000, size 3000, prot 0, flags 4032, fd -1, offset 0
        2    fixed at 7002001000
        2    anon nomap target: 7002001000, len: 3000 (given size: 3000)
        2 direct return: 481069895680, rsp 0x70020ffc68
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ffba8
        2 rt_sigprocmask
        2 direct return: 0, rsp 0x70020ffc70
        2 sched_getaffinity
        2 direct return: 0, rsp 0x70020ffa68
        2 sched_getaffinity
        2 direct return: 0, rsp 0x70020ffa68
        2 gettid
        2 direct return: 2, rsp 0x70020ffd08
        2 rt_sigprocmask
        2 direct return: 0, rsp 0x70020ffbc0
        2 rt_sigprocmask
        2 direct return: 0, rsp 0x70020ffbc0
        2 rt_sigprocmask
        2 direct return: 0, rsp 0x70020ffbc0
        2 mmap
        2 mmap: target 0x0000007002001000, size 3000, prot 3, flags 32, fd -1, offset 0
        2    fixed at 7002001000
        2    anon nomap target: 7002001000, len: 3000 (given size: 3000)
        2 direct return: 481069895680, rsp 0x70020ffb98
        2 mprotect
        2 direct return: 0, rsp 0x70020ffcf8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ffbf8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ffaf8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ffbf8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ffb28
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ffb28
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ffb28
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff5a8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff788
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff788
        2 lseek
        2 lseek: fd 3 offset 59530732 whence SEEK_SET
        2 direct return: 59530732, rsp 0x70020ff168
        2 read
        2 file_read: f 0x00000001000241b0, dest 0x00000070020ff1a0, offset 59530732 (file), length 30, file length 65018124
        2 sleep
        2 file_op_complete: len 30, status (none) (OK)
        2 wakeup 2->2 0x0000007000011544
        2 run frame 0x0000000100202400, RIP=0x0000007000011544
        2 lseek
        2 lseek: fd 3 offset 59530786 whence SEEK_SET
        2 direct return: 59530786, rsp 0x70020ff1b8
        2 read
        2 file_read: f 0x00000001000241b0, dest 0x0000007038001090, offset 59530786 (file), length 2959, file length 65018124
        2 sleep
        2 file_op_complete: len 2959, status (none) (OK)
        2 wakeup 2->2 0x0000007000011544
        2 run frame 0x0000000100202400, RIP=0x0000007000011544
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff768
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff768
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff4c8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff4e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff398
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff4c8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff4c8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff698
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ffb28
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff808
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff828
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff808
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff808
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff828
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff808
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff808
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff808
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff808
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff808
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff938
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff958
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fec08
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fed78
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fed78
        2 gettimeofday
        2 direct return: 0, rsp 0x70020feca8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020feca8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020feca8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe728
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe908
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe908
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe908
        2 lseek
        2 lseek: fd 3 offset 59530296 whence SEEK_SET
        2 direct return: 59530296, rsp 0x70020fe2e8
        2 read
        2 file_read: f 0x00000001000241b0, dest 0x00000070020fe320, offset 59530296 (file), length 30, file length 65018124
        2 sleep
        2 file_op_complete: len 30, status (none) (OK)
        2 wakeup 2->2 0x0000007000011544
        2 run frame 0x0000000100202400, RIP=0x0000007000011544
        2 lseek
        2 lseek: fd 3 offset 59530355 whence SEEK_SET
        2 direct return: 59530355, rsp 0x70020fe338
        2 read
        2 file_read: f 0x00000001000241b0, dest 0x0000007008009000, offset 59530355 (file), length 377, file length 65018124
        2 sleep
        2 file_op_complete: len 377, status (none) (OK)
        2 wakeup 2->2 0x0000007000011544
        2 run frame 0x0000000100202400, RIP=0x0000007000011544
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe8e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe8e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe8e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe648
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe648
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe668
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe518
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe648
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe648
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe648
        2 gettimeofday
        2 direct return: 0, rsp 0x70020fe818
        2 gettimeofday
        2 direct return: 0, rsp 0x70020feca8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff2e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff2e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff308
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff2e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff2e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff308
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff2e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff2e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff2e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff2e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff2e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff2e8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff418
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff438
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff418
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff418
        2 gettimeofday
        2 direct return: 0, rsp 0x70020feb08
        2 gettimeofday
        2 direct return: 0, rsp 0x70020feab8
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff938
        2 gettimeofday
        2 direct return: 0, rsp 0x70020ff938
        2 futex
        2 futex_wake [2 0x00000070080ac37c 2] 0x0000000100204400 1/1
        2 wakeup 2->10 0x000000700000e35b
        2 direct return: 1, rsp 0x70020ffc50
        2 futex
        2 futex_wait [2 0x0000007008009878 0] 0 0x0000000000000000
        2 sleep
                                                                        10 run frame 0x0000000100204400, RIP=0x000000700000e35b
                                                                        10 futex
                                                                        10 direct return: 0, rsp 0x7024cffbe0
                                                                        10 gettimeofday
                                                                        10 direct return: 0, rsp 0x7024cffd78
                                                                        10 gettimeofday
                                                                        10 direct return: 0, rsp 0x7024cffd38
                                                                        10 gettimeofday
                                                                        10 direct return: 0, rsp 0x7024cffbc8
                                                                        10 futex
                                                                        10 futex_wake [10 0x000000700806d67c 2] 0x0000000100202800 1/1
                                                                        10 wakeup 10->3 0x000000700000e35b
                                                                        10 direct return: 1, rsp 0x7024cffb80
                                                                        10 futex
                                                                        10 futex_wake [10 0x0000007008009878 2] 0x0000000100202400 1/1
                                                                        10 wakeup 10->2 0x000000700000e00c
                                                                        10 direct return: 1, rsp 0x7024cffd90
                                                                        10 madvise
                                                                        10 direct return: 0, rsp 0x7024cffef8
                                                                        10 exit
                3 run frame 0x0000000100202800, RIP=0x000000700000e35b
                3 futex
                3 direct return: 0, rsp 0x70036ffae0
                3 gettimeofday
                3 direct return: 0, rsp 0x70036ffa78
                3 gettimeofday
                3 direct return: 0, rsp 0x70036ffba8
                3 gettimeofday
                3 direct return: 0, rsp 0x70036ffba8
                3 mprotect
                3 direct return: 0, rsp 0x70036ffbe8
                3 mprotect
                3 direct return: 0, rsp 0x70036ffbe8
                3 mprotect
                3 direct return: 0, rsp 0x70036ffc08
                3 futex
                3 futex_wait [3 0x000000700806d678 0] 0 0x0000000000000000
                3 sleep
        2 run frame 0x0000000100202400, RIP=0x000000700000e00c
        2 futex
        2 direct return: 0, rsp 0x70020ffb50
        2 futex
        2 futex_wait [2 0x000000700800987c 0] 0 0x0000000000000000
        2 sleep
```

**Comment by francescolavra** [comment] 2021-01-04 12:30
I'm unable to reproduce the issues with current master. (I couldn't test with `ops run` by specifying my local JVM installation dir and Java binary, because when run in this way it errors out with `Exception in thread "main" java.lang.AssertionError: Platform not recognized`). Tested with `ops load java_1.8.0_191 -m openjre8-hello.manifest -c openjre8-hello.json -v -d > log.txt` (after removing from the json file my local JVM installation dir), it runs to completion and exits without hanging, and in the log.txt output file there are no page faults.

**Comment by eyberg** [comment] 2021-03-24 15:42
can't repro anymore - closing

**Closed by eyberg** 2021-03-24 15:42 UTC
Labels: jvm
