### ISSUE TITLE
fs_full test sometimes fails on ARM with strange read result and a misaligned buffer error

### ISSUE THREAD

**Issue by sanderssj** [nanovms/nanos#1473] opened 2021-05-07 16:26 UTC
This failed in CI, but only once in quite a few CI runs. Failed at commit https://github.com/nanovms/nanos/commit/7b1bfa6692d30c78a6da6d6a9226561c8f997c54
```
MKFS	image
UUID: df8c5f0f-ebec-6018-181c-8874ec4a7f22
metadata
(children:(kernel:()))
UUID: 895b723d-4e6b-85c0-cf3f-341631692e0e
metadata
(arguments:(0:fs_full)
 children:(fs_full:())
 environment:(PWD:/
              USER:bobby)
 fault:t
 program:/fs_full)
qemu-system-aarch64 -machine virt -machine gic-version=2 -machine highmem=off -m 1G  -kernel /home/circleci/project/output/platform/virt/bin/kernel.img -display none  -serial stdio -drive if=none,id=hd0,format=raw,file=/home/circleci/project/output/image/disk.raw -device virtio-blk-pci,drive=hd0 -no-reboot -semihosting  -device virtio-net,netdev=n0 -netdev user,id=n0,hostfwd=tcp::8080-:8080,hostfwd=tcp::9090-:9090,hostfwd=udp::5309-:5309 -object filter-dump,id=filter0,netdev=n0,file=/tmp/nanos.pcap -cpu max
en1: assigned 10.0.2.15
total bytes: 121634816 free bytes: 120520704 blocksize: 512
en1: assigned FE80::5054:FF:FE12:3456
failed to read written block 40155 err 'Success'
fs_full: /home/circleci/project/test/runtime/fs_full.c:93: main: Assertion `statbuf.f_bfree < MAX_FREE_BYTES/BLOCKSIZE' failed.
signal 6 received by tid 1, errno 0, code -6
   core dump (unimplemented)
storage_rw_internal error: misaligned buf: 0xffffffff802b8228
storage_rw_internal error: write buffer not properly aligned
make[2]: *** [Makefile:337: run-noaccel] Error 127
make[2]: Leaving directory '/home/circleci/project/platform/virt'
make[1]: *** [Makefile:103: run-noaccel] Error 2
make[1]: Leaving directory '/home/circleci/project'
```

**Comment by wjhun** [comment] 2021-05-13 20:46
I have a hunch for the cause of this issue (aside from the misaligned error which was fixed in #1480). When running the fs_full test on the Raspberry Pi 4, I am seeing a log rebuild being triggered, followed by a call to flush_log_extension and ensuring write to storage. The storage completion does not occur for quite a while (at least five or more seconds later) and, in the meantime, the log's tuple_staging buffer fills up, causing a write to log_write_eav to fail during file extent allocation (actually an "extend"), and ultimately the fs_fill test to fail and exit.

When I add some debugs to monitor virtqueue activity, I see that a lot of requests are being queued up, creating a sizable backlog. The requests filter out, draining the the virtqueue's msg_queue, but somewhat sporadically. Even after fs_full fails, the VM still stays up for several seconds while the writes drain out, pending completion of the final log flush. It makes sense, then, that the log flush would take so long; it is being held up by a large backlog of storage requests which are being served rather slowly.

I think this could be indicative of a driver-level problem, as it seems odd that there should be such a backlog and slow drain of storage requests from a meager 128MB amount of writes. However, this also points to a robustness issue in the log code, as the system should be tolerant of a delay in storage activity while a log compaction is taking place.

Also - I just found that this is occurring on the PC, too, when STORAGE=virtio-blk. So the slow storage performance is likely an issue with the virtio-storage driver, which is used by default for the virt platform. virtio-scsi currently isn't probing on virt - I'm looking into this.

**Closed** 2021-05-24 17:14 UTC
Labels: arm
