### ISSUE TITLE
/proc/self/exe is found via readlink but stat throws an error

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1167] opened 2020-05-05 16:52 UTC
```
 ops load node_v13.6.0 -x -d -c config.js -a bob.js &> /tmp/bob
```

```
const fs = require('fs');
const path = require('path');
const {
  inspect,
} = require('util');

const tree = {};

const dtree = async (dir, result) => {
  const isDirectory = fs.statSync(dir).isDirectory();
  const p = path.parse(dir);

  if (isDirectory === true) {
    result[p.base] = [];

    const files = await fs.promises.readdir(dir, {
      withFileTypes: true,
    });
    // eslint-disable-next-line no-restricted-syntax
    for await (const file of files) {
      const fsObjectPath = path.resolve(dir, file.name);

      await dtree(fsObjectPath, result[p.base]);
    }
  }

  if (isDirectory === false) {
    result.push(p.base);
  }
};

dtree(path.resolve('/'), tree).then(() => {
  console.error(
    inspect(tree, {
      showHidden: false,
      depth: null,
      colors: true,
    }),
  );
});
```

```
 cat config.js
{
  "Dirs": ["node_modules"],
  "Env": {
    "NODE_DEBUG": "*",
    "NODE_DEBUG_NATIVE": "*"
  },
  "Files": ["bob.js", "package.json", "pnpm-lock.yaml"]
}
```

```
ESM 2: Storing file:///bob.js in ModuleMap
(node:2) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/proc/self/exe'
    at Object.statSync (fs.js:948:3)
    at dtree (/bob.js:10:26)
    at dtree (/bob.js:23:13)
    at async dtree (/bob.js:23:7)
    at async dtree (/bob.js:23:7)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
exit status 1
```

```
1 readlink
1 readlink: "/proc/self/exe"
1 direct return: 17, rsp 0x76c66948
```

```
1 stat
1 stat: "/proc/self/exe", buf 0x0000000076c643b0
1 direct return: -2, rsp 0x76c64378
```

https://github.com/nanovms/nanos/commit/61e91ee566c825b42786f37b3a95b586fb1c67f4
https://github.com/nanovms/nanos/commit/e81bc008b9f84b12d467903efbb0d8a7e590f1f4

**Comment by francescolavra** [comment] 2020-05-07 15:45
The commit (https://github.com/nanovms/nanos/commit/61e91ee566c825b42786f37b3a95b586fb1c67f4) that fixed this is more recent than the latest Nanos release 0.1.25.
If you use the nightly build it should work fine.

**Comment by eyberg** [comment] 2020-05-07 15:47
that's only for ref - i'm reproducing this on master

**Comment by eyberg** [comment] 2020-05-07 15:58
2d88cadea33f9a8f535ceb06c5eea6a74216badd is what i'm looking at - I guess to add the missing color here 

if you run this without any node_modules you are right it seems to exit fine, however, as soon as I add a node_module w/pnpm (npm replacement) it runs into this error

```
curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
pnpm install redis-fast-driver --save
```

**Comment by eyberg** [comment] 2020-05-07 16:31
hrm -- this could just be my lack of knowledge on how node works

specifying any other directory like '/node_modules' seems to work but passing the root path didn't '/'

I wrapped the tree walker w/try/catch to get around the issue for now 

```
const fs = require('fs');
const path = require('path');
const {
  inspect,
} = require('util');

const tree = {};

const dtree = async (dir, result) => {
  try {
  const isDirectory = fs.statSync(dir).isDirectory();
  const p = path.parse(dir);

  if (isDirectory === true) {
    result[p.base] = [];

    const files = await fs.promises.readdir(dir, {
      withFileTypes: true,
    });
    // eslint-disable-next-line no-restricted-syntax
    for await (const file of files) {
      const fsObjectPath = path.resolve(dir, file.name);

      await dtree(fsObjectPath, result[p.base]);
    }
  }

  if (isDirectory === false) {
    result.push(p.base);
  }

  } catch(err) {
  }

};

dtree(path.resolve('/'), tree).then(() => {
  console.error(
    inspect(tree, {
      showHidden: false,
      depth: null,
      colors: true,
    }),
  );
});
```

i suppose you can close this if you want

**Comment by francescolavra** [comment] 2020-05-07 16:45
I'm unable to reproduce the issue, if I run the command it seems to complete without any errors. The relevant bits of the debug log I get are:
```
1 readlink
1 readlink: "/proc/self/exe"
1 readlink: returning "node_v13.6.0/node"
1 direct return: 17, rsp 0x76e11948
```
```
1 stat
1 stat: "/node_v13.6.0/node", buf 0x0000000076e0f3b0
1 st_ino 20000004240, st_mode 0x81a4, st_size 44b7620
1 direct return: 0, rsp 0x76e0f378
```
In my log  couldn't find any `stat: "/proc/self/exe"`.

**Comment by eyberg** [comment] 2020-05-07 17:19
@francescolavra I ran this locally and node complained about /dev/fd files so I think we can chalk this up to how node deals w/special files

**Comment by Dmitry-N-Medvedev** [comment] 2020-05-07 17:28
@eyberg, @francescolavra,

if you like I can create a simple repo with NodeJS project under the pnpm for you to use it for tests.

**Comment by eyberg** [comment] 2020-05-07 18:22
@Dmitry-N-Medvedev - I was able to trim down your original problem - https://github.com/nanovms/nanos/issues/1169 - i'll respond in the other tkt you have

**Comment by francescolavra** [comment] 2020-05-10 08:55
`stat("/proc/self/exe")` works fine when used in a C program.
Closing.

**Closed by francescolavra** 2020-05-10 08:55 UTC
Labels: node
