### ISSUE TITLE
Clean shutdown VM instance on GCP

### ISSUE THREAD

**Issue by nielsbergsma** [nanovms/nanos#1874] opened 2023-06-14 19:46 UTC
Dear NanoVMs-team,

I running a stateful service running on GCP, with an attached volume. I'd like to flush uncommitted changes when the VM gets shutdown. For this, I've added a handler for SIGINT/SIGTERM signals. However, when inspecting the serial console, I see a trace message being reported. 

Is there anything I need to configure?

Below are the first lines on the serial output. It continues to repeat the `frame trace: ...` message for a while.

```
SeaBIOS (version 1.8.2-google)
Total RAM Size = 0x000000006cc00000 = 1740 MiB
CPUs found: 1     Max CPUs supported: 1
found virtio-scsi at 0:3
virtio-scsi vendor='Google' product='PersistentDisk' rev='1' type=0 removable=0
virtio-scsi blksize=512 sectors=2097152 = 1024 MiB
virtio-scsi vendor='Google' product='PersistentDisk' rev='1' type=0 removable=0
virtio-scsi blksize=512 sectors=20971520 = 10240 MiB
drive 0x000f2890: PCHS=0/0/0 translation=lba LCHS=1024/32/63 s=2097152
drive 0x000f2850: PCHS=0/0/0 translation=lba LCHS=1024/255/63 s=20971520
Sending Seabios boot VM event.
Booting from Hard Disk 0...
en1: assigned 10.164.0.47
mounts: Ok("root / tfs rw 0 0\ndata-disk /data tfs rw 0 0\n")
en1: assigned FE80::4001:AFF:FEA4:2F
waiting for network to become ready
waiting for network to become ready

frame trace: 
ffffc00000a47dd8:   ffffffff80045ab2	(mutex_lock + 0000000000000012/000000000000003c)
ffffc00000a47de8:   ffffffff80091184	(fs_cache_sync_complete + 0000000000000204/000000000000028b)
ffffc00000a47e58:   ffffffff80057199	(storage_sync + 0000000000000049/00000000000000ff)
ffffc00000a47e98:   ffffffff800401f7	(kernel_shutdown + 0000000000000167/0000000000000400)
ffffc00000a47ef8:   ffffffff8002fdcf
ffffc00000a47f08:   ffffffff8000abd7	(AcpiEvFixedEventDetect + 00000000000000b7/0000000000000104)
ffffc00000a47f48:   ffffffff8000d6a7	(AcpiEvSciXruptHandler + 0000000000000017/0000000000000087)
ffffc00000a47f78:   ffffffff80112a69	(shirq_handler + 0000000000000029/000000000000003c)
ffffc00000a47f98:   ffffffff80113031	(common_handler + 0000000000000251/0000000000000573)
ffffc00000a47fe8:   ffffffff800011a0
ffffc00000a37fc0:   ffffffff80040e43	(context_switch_finish + 0000000000000073/000000000000019f)

loaded klibs: 
assertion !frame_is_full(ctx->frame) failed at /home/eyberg/go/src/github.com/nanovms/nanos/src/kernel/mutex.c:109  in mutex_lock_internal(); halt

frame trace: 
ffffc00000a47968:   ffffffff80045ab2	(mutex_lock + 0000000000000012/000000000000003c)
ffffc00000a47978:   ffffffff80091184	(fs_cache_sync_complete + 0000000000000204/000000000000028b)
ffffc00000a479e8:   ffffffff80057199	(storage_sync + 0000000000000049/00000000000000ff)
ffffc00000a47a28:   ffffffff800401f7	(kernel_shutdown + 0000000000000167/0000000000000400)
ffffc00000a47a88:   ffffffff80040dce
ffffc00000a47d88:   ffffffff800459a8	(mutex_lock_internal + 0000000000000308/00000000000003b4)
ffffc00000a47dd8:   ffffffff80045ab2	(mutex_lock + 0000000000000012/000000000000003c)
ffffc00000a47de8:   ffffffff80091184	(fs_cache_sync_complete + 0000000000000204/000000000000028b)
ffffc00000a47e58:   ffffffff80057199	(storage_sync + 0000000000000049/00000000000000ff)
ffffc00000a47e98:   ffffffff800401f7	(kernel_shutdown + 0000000000000167/0000000000000400)
ffffc00000a47ef8:   ffffffff8002fdcf
ffffc00000a47f08:   ffffffff8000abd7	(AcpiEvFixedEventDetect + 00000000000000b7/0000000000000104)
ffffc00000a47f48:   ffffffff8000d6a7	(AcpiEvSciXruptHandler + 0000000000000017/0000000000000087)
ffffc00000a47f78:   ffffffff80112a69	(shirq_handler + 0000000000000029/000000000000003c)
ffffc00000a47f98:   ffffffff80113031	(common_handler + 0000000000000251/0000000000000573)
ffffc00000a47fe8:   ffffffff800011a0
ffffc00000a37fc0:   ffffffff80040e43	(context_switch_finish + 0000000000000073/000000000000019f)
...
```

**Comment by francescolavra** [comment] 2023-06-15 09:16
@nielsbergsma no, there is nothing you need to configure, this is a bug in the kernel, which will be fixed by #1875.
Please note that Nanos does not send any signal to the user program when a VM is shut down, so your SIGINT/SIGTERM signal handler will not be invoked; however, Nanos takes care of flushing all files written by the program, either directly or via memory mappings, even if they are not flushed explicitly via e.g. fsync().

**Comment by nielsbergsma** [comment] 2023-06-15 17:14
Hi @francescolavra, thanks for confirming and creating a bug report. 

It would be useful to have some kind of mechanism (in the future) that signals to the program that it's terminating and gives it certain amount of time to gracefully shut down. In my case I have a RocksDB storage engine, and I'm not 100% sure that flushing will persist all the changes correctly.

**Comment by nielsbergsma** [comment] 2023-06-16 14:45
Great, thanks @francescolavra for your prompt response! I'll add a new ticket for the shutdown event.

**Comment by nielsbergsma** [comment] 2023-06-20 20:03
Hi @francescolavra,

I'm afraid the original issue still persists. I've tested with creating a custom kernel based on the master branch. The trace is no longer printed, but the volume is not closed correctly. 

To summarize; using a attached volume gets corrupted after reboot. I've created a minimal reproducible example [here](https://github.com/nielsbergsma/nanos-rocksdb-problem). The first runs completes successfully. The second one, errors out while opening the database. The output looks like:

```
en1: assigned 10.0.2.15
ingest_extent error: unable to reserve storage blocks [0xc19 0xc21)
thread 'main' panicked at 'unable to open rocksdb database: Error { message: "Corruption: While creating a new Db, wal_dir contains existing log file: : 000008.log" }', src/main.rs:6:10
```

I've noted that:
- this is reproducible locally (doesn't seem cloud vendor specific)
- is not does happen with nanos 1.44

**Comment by francescolavra** [comment] 2023-06-21 11:23
Thanks for providing an example, I can reproduce the issue and I'm looking into it

**Comment by francescolavra** [comment] 2023-06-21 14:12
Found the cause of the problem, will be fixed by https://github.com/nanovms/nanos/pull/1882.

**Closed** 2023-06-22 08:29 UTC

**Comment by nielsbergsma** [comment] 2023-06-22 18:00
Awesome work!, will check it asap, together with https://github.com/nanovms/nanos/pull/1880

**Comment by nielsbergsma** [comment] 2023-06-24 09:18
I checked this change this morning and it works great! thanks @francescolavra
