### ISSUE TITLE
investigate eval'ng graalvm

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1072] opened 2020-02-07 15:44 UTC
was just asked about it on drift - uses AOT to produce a 'native image' to run jvm programs w/out boot time and also runs many other languages in a one runtime to rule them all env

https://www.graalvm.org/docs/getting-started/

**Comment by eyberg** [comment] 2020-02-07 16:16
```
export PATH=/home/eyberg/graal/graalvm-ee-java11-19.3.1/bin:$PATH
gu -L install native-image-installable-svm-svmee-java11-linux-amd64-19.3.1.jar
```

```
eyberg@box:~/c$ cat Bob.java
public class Bob {

    public static void main(String[] args) {
      System.out.println("yo");
    }

}
```

```
javac Bob.java
native-image --no-server --no-fallback Bob
```

```
1 mmap
1 mmap: target 0x0000000000000000, size 0x800000000, len 0x0, prot 0x0, flags 0x4022, fd -1, offset 0x0
mmap error: failed to allocate  virtual memory, size 0x0
1 direct return: -12, rsp 0x76ed1cf8
1 fcntl
1 fcntl: fd 2, cmd 3, arg -128
1 direct return: 2, rsp 0x76ed1cc0
1 fstat
1 fd 2, stat 0x0000000076ed15e0
1 st_ino 0, st_mode 0x1000, st_size 0
1 direct return: 0, rsp 0x76ed15d8
1 write
Fatal error: Failed to create a new Isolate. (code 8)
1 direct return: 54, rsp 0x76ed1bb8
1 exit_group
exit status 17
eyberg@box:~/c$
```

**Comment by eyberg** [comment] 2020-02-07 18:37
mmap works w/ https://github.com/nanovms/nanos/commit/52374af66410032a2b768151c1bca582abe857ab although it fails when trying to read /proc/self/maps

```
1 mmap: target 0x0000000000000000, size 0x800000000, len 0x800000000, prot 0x0, flags 0x4022, fd -1, offset 0x0
1    anon target: 0x1000000000, len: 0x800000000 (given size: 0x800000000)
1 direct return: 68719476736, rsp 0x76c47cf8
1 openat
1 "/proc/self/maps" - not found
1 direct return: -2, rsp 0x76c47b20
1 munmap
1 munmap: addr 0x0000001000000000, size 0x800000000
1 direct return: 0, rsp 0x76c47d28
1 fcntl
1 fcntl: fd 2, cmd 3, arg -128
1 direct return: 2, rsp 0x76c47cc0
1 fstat
1 fd 2, stat 0x0000000076c475e0
1 st_ino 0, st_mode 0x1000, st_size 0
1 direct return: 0, rsp 0x76c475d8
1 write
Fatal error: Failed to create a new Isolate. (code 6)
```

**Comment by eyberg** [comment] 2020-02-07 19:02
there's def. a few programs that want to read from this but proc is such a slippery slope and very linux specific - if we add support some things where does it stop?

seems osv thought it was necessary enough (although only looks like they add 3 or 4 pseudo files)

https://github.com/cloudius-systems/osv/blob/287c379ae35a96b6c19179e9fa4a191099aa6295/fs/procfs/procfs_vnops.cc#L165

https://github.com/cloudius-systems/osv/blob/fe61b3133a2941e1f7e32b3fc86c6b3cabc14cf8/core/mmu.cc#L1921-L1944

**Comment by francescolavra** [comment] 2020-06-14 16:11
Even after adding support for /proc/self/maps, it fails with `Fatal error: Failed to create a new Isolate. (code 6)`. The reason is that we don't store in the memory map the association between mappings and corresponding files, and as a result what the application reads from /proc/self/maps doesn't have the info about inode numbers and file paths. graalVM at initialization locates the backing file of the image heap, then opens the file by its path and verifies that the file matches the inode associated with the mapping (see the `LinuxImageHeapProvider::initialize()` method at https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/LinuxImageHeapProvider.java).
When file-backed user mappings are fully implemented, we will probably have the info we need to export to userspace file path and inode number associated to each mapping.

**Comment by eyberg** [comment] 2020-06-15 14:38
https://github.com/nanovms/nanos/issues/1113

**Comment by francescolavra** [comment] 2021-05-16 09:30
The latest version of GraalVM Enterprise Edition works fine: even though Nanos still doesn't store info about inode numbers and file paths in /proc/self/maps, the graalVM initialization process has changed and no longer needs that info, so the runtime now loads correctly. Tested with graalvm-ee-java11-21.1.0.
```
francesco@ubuntu:~/Documents/NanoVMs/graalvm$ ops run bob
booting /home/francesco/.ops/images/bob.img ...
en1: assigned 10.0.2.15
yo
```

**Comment by francescolavra** [comment] 2021-06-28 06:48
Confirmed it works with latest Nanos release and nightly build. Closing

**Closed by francescolavra** 2021-06-28 06:48 UTC
Labels: needs investigation, proc
